# Generated by Django 4.2.25 on 2025-10-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingType', models.CharField(blank=True, max_length=20, null=True)),
                ('PickupLocation', models.CharField(blank=True, max_length=300, null=True)),
                ('DropLocation', models.CharField(blank=True, max_length=300, null=True)),
                ('NoOfPassengers', models.IntegerField(blank=True, null=True)),
                ('BookingStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('BookingDate', models.DateField(auto_now_add=True, null=True)),
                ('OtpCode', models.CharField(blank=True, max_length=10, null=True)),
                ('DeliveyItem', models.CharField(blank=True, max_length=300, null=True)),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('DeliveyDetails', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Place', models.CharField(blank=True, max_length=30, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRouteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartLocation', models.CharField(blank=True, max_length=300, null=True)),
                ('EndLocation', models.CharField(blank=True, max_length=300, null=True)),
                ('WayPoint', models.CharField(blank=True, max_length=20, null=True)),
                ('Distance_Km', models.FloatField(blank=True, null=True)),
                ('StartingTime', models.DateTimeField(blank=True, null=True)),
                ('EndingTime', models.DateTimeField(blank=True, null=True)),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=10, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('TransactionDate', models.DateField(auto_now_add=True)),
                ('BOOKINGID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.bookingtable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Comment', models.CharField(blank=True, max_length=500, null=True)),
                ('FeedbackDate', models.DateField(auto_now_add=True)),
                ('BOOKINGID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.bookingtable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Reply', models.CharField(blank=True, max_length=300, null=True)),
                ('ComplaintDate', models.DateField(auto_now_add=True)),
                ('BOOKINGID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.bookingtable')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable'),
        ),
    ]
