# Generated by Django 4.2.25 on 2025-11-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='DeliveyDetails',
            new_name='DeliveryDetails',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='TRAVELERID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='booking_traveler', to='CordApp.usertable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='TRAVELERID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='route_traveler', to='CordApp.usertable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to='CordApp.usertable'),
        ),
        migrations.AlterField(
            model_name='travelroutetable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_user', to='CordApp.usertable'),
        ),
    ]
