# Generated by Django 4.2.26 on 2025-12-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0002_rename_deliveydetails_bookingtable_deliverydetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelroutetable',
            name='RideType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
