# Generated by Django 4.2.26 on 2025-12-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0003_travelroutetable_ridetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='TRAVELERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.travelroutetable'),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable'),
        ),
    ]
