# Generated by Django 4.2.26 on 2025-12-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0004_alter_bookingtable_travelerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelroutetable',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
