# Generated by Django 4.2.26 on 2025-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0005_travelroutetable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='RideAvailability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
