# Generated by Django 4.2.27 on 2025-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0006_bookingtable_rideavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='SpaceAvailability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
