# Generated by Django 4.2.27 on 2025-12-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0007_bookingtable_spaceavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelroutetable',
            name='Distance_Km',
        ),
        migrations.RemoveField(
            model_name='travelroutetable',
            name='WayPoint',
        ),
    ]
