# Generated by Django 4.2.27 on 2025-12-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0008_remove_travelroutetable_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='NoOfPassengers',
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='RideAvailability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='SpaceAvailability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
