# Generated by Django 4.2.27 on 2025-12-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0009_remove_bookingtable_noofpassengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelroutetable',
            name='USERID',
        ),
        migrations.AlterField(
            model_name='travelroutetable',
            name='TRAVELERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_traveler', to='CordApp.usertable'),
        ),
    ]
