# Generated by Django 4.2.27 on 2025-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0010_remove_travelroutetable_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelroutetable',
            name='EndingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelroutetable',
            name='StartingTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
