# Generated by Django 4.2.27 on 2025-12-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0011_alter_travelroutetable_endingtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='DeliveryDetails',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='DeliveyItem',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='RideAvailability',
        ),
        migrations.RemoveField(
            model_name='bookingtable',
            name='SpaceAvailability',
        ),
    ]
