# Generated by Django 4.2.26 on 2025-12-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0012_remove_bookingtable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='BookingType',
        ),
    ]
