# Generated by Django 4.2.26 on 2025-12-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0013_remove_bookingtable_bookingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='TRAVELERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.travelroutetable'),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.logintable'),
        ),
    ]
