# Generated by Django 4.2.27 on 2026-01-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0014_alter_bookingtable_travelerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintstable',
            name='Subject',
        ),
    ]
