# Generated by Django 4.2.27 on 2026-01-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0017_alter_chattable_receiver_alter_chattable_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattable',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='CordApp.usertable'),
        ),
        migrations.AlterField(
            model_name='chattable',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='CordApp.usertable'),
        ),
    ]
