# Generated by Django 4.2.27 on 2026-01-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0018_alter_chattable_receiver_alter_chattable_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelroutetable',
            name='Created_At',
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='Kms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelroutetable',
            name='VehicleType',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='BookingStatus',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
