# Generated by Django 4.2.27 on 2026-01-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0020_travelroutetable_bagsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='ProfilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
