# Generated by Django 4.2.27 on 2026-01-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0021_usertable_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='ParcelImage',
            field=models.ImageField(blank=True, null=True, upload_to='parcels/'),
        ),
    ]
