# Generated by Django 5.2.10 on 2026-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0023_alter_bookingtable_parcelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttable',
            name='USERID',
        ),
    ]
