# Generated by Django 5.2.10 on 2026-01-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0024_remove_paymenttable_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tip', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_At', models.DateField(auto_now_add=True)),
                ('BOOKING', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CordApp.bookingtable')),
            ],
        ),
    ]
