# Generated by Django 5.2.10 on 2026-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0025_tiptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='IdProof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
