# Generated by Django 5.2.10 on 2026-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0026_usertable_idproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
