# Generated by Django 4.2.27 on 2026-01-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0027_alter_logintable_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='PaymentProof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='PaymentStatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='UTR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
