# Generated by Django 5.2.10 on 2026-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0028_bookingtable_paymentproof_bookingtable_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='UTR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
