# Generated by Django 5.2.10 on 2026-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0029_alter_bookingtable_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='UpiId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
