# Generated by Django 5.2.10 on 2026-02-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0030_usertable_upiid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('UTR', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('TRAVELER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable')),
            ],
        ),
    ]
