# Generated by Django 4.2.7 on 2026-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0031_settlementtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttable',
            name='TransactionType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
