# Generated by Django 4.2.7 on 2026-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0032_alter_paymenttable_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttable',
            name='TransactionType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
