# Generated by Django 4.2.7 on 2026-03-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CordApp', '0033_alter_paymenttable_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtable',
            name='SettlementProof',
            field=models.FileField(blank=True, null=True, upload_to='settlements/'),
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=500)),
                ('IsRead', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CordApp.usertable')),
            ],
        ),
    ]
