# # """
# # Django settings for Cord project.

# # Generated by 'django-admin startproject' using Django 4.2.25.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/4.2/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/4.2/ref/settings/
# # """
# # import dj_database_url
# # import os
# # from pathlib import Path

# # # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # Quick-start development settings - unsuitable for production
# # # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# # # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-g^-g!!08#5_(3agt4+=i=(o@miqp8jhx)4hazka(4c2+%t=z42'

# # # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True

# # ALLOWED_HOSTS = ['*']


# # # Application definition

# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     'CordApp',
# #     'rest_framework',   
# # ]

# # MIDDLEWARE = [
# #     'django.middleware.security.SecurityMiddleware',
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# # ]

# # ROOT_URLCONF = 'Cord.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [os.path.join(BASE_DIR, 'templates')],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # WSGI_APPLICATION = 'Cord.wsgi.application'


# # # Database
# # # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# # # DATABASES = {
# # #     'default': {
# # #         'ENGINE': 'django.db.backends.sqlite3',
# # #         'NAME': BASE_DIR / 'db.sqlite3',
# # #     }
# # # Database Configuration
# # # https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# # DATABASES = {
# #     'default': dj_database_url.config(
# #         # This is your local backup. If DATABASE_URL is not found (like on your laptop),
# #         # it defaults to using your local sqlite3 file.
# #         default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
# #         conn_max_age=600
# #     )
# # }


# # # Password validation
# # # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
# #     },
# # ]


# # # Internationalization
# # # https://docs.djangoproject.com/en/4.2/topics/i18n/

# # LANGUAGE_CODE = 'en-us'

# # TIME_ZONE = 'UTC'

# # USE_I18N = True

# # USE_TZ = True


# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/4.2/howto/static-files/

# # STATIC_URL = 'static/'

# # # Default primary key field type
# # # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider's SMTP server
# # EMAIL_PORT = 587  # Typically 587 for TLS, or 465 for SSL
# # EMAIL_USE_TLS = True  # Use TLS (True if PORT=587)
# # EMAIL_USE_SSL = False  # Set True if PORT=465
# # EMAIL_HOST_USER = 'saanandsdb@gmail.com'  # Your email address
# # EMAIL_HOST_PASSWORD = 'chhu bboa dizs vfvg'

# # # Add this at the bottom of settings.py //media settings
# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # # settings.py

# # # You get these from your Stripe Dashboard (Developers > API Keys)
# # STRIPE_PUBLISHABLE_KEY = "pk_test_your_key_here"
# # STRIPE_SECRET_KEY = "sk_test_your_secret_key_here"  


# """
# Django settings for Cord project.
# Updated for Render Deployment + Flutter Support
# """
# import dj_database_url
# import os
# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # =========================================================
# # SECURITY SETTINGS
# # =========================================================

# # 1. SECRET_KEY: Try to get it from Render. If not found, use the insecure local one.
# SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-g^-g!!08#5_(3agt4+=i=(o@miqp8jhx)4hazka(4c2+%t=z42')

# # 2. DEBUG: Disable Debug mode on Render (Production), keep True locally
# # Render automatically sets the 'RENDER' environment variable.
# if 'RENDER' in os.environ:
#     DEBUG = False
# else:
#     DEBUG = True

# ALLOWED_HOSTS = ['*'] # Required for Render

# # =========================================================
# # APPLICATION DEFINITION
# # =========================================================

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
    
#     # Third Party Apps
#     'rest_framework',
#     'corsheaders',  # <--- ADDED FOR FLUTTER
    
#     # Your Apps
#     'CordApp',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- ADDED: Must be right after SecurityMiddleware
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'corsheaders.middleware.CorsMiddleware',       # <--- ADDED: Must be before CommonMiddleware
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'Cord.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'Cord.wsgi.application'

# # =========================================================
# # DATABASE
# # =========================================================

# DATABASES = {
#     'default': dj_database_url.config(
#         # Local fallback (SQLite)
#         default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
#         conn_max_age=600
#     )
# }

# # =========================================================
# # PASSWORDS & I18N
# # =========================================================

# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

# # =========================================================
# # STATIC FILES (CSS, JS, Images) - CRITICAL FOR RENDER
# # =========================================================

# STATIC_URL = '/static/'

# # This tells Django where to collect files when you run 'collectstatic'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # Enable Whitenoise compression and caching
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# # Media Files (User Uploads)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # =========================================================
# # CORS SETTINGS (For Flutter)
# # =========================================================

# # Allow all origins so your mobile app can connect easily
# CORS_ALLOW_ALL_ORIGINS = True 

# # =========================================================
# # EMAIL SETTINGS
# # =========================================================

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'saanandsdb@gmail.com'
# # Ideally, move this password to an environment variable too!
# EMAIL_HOST_PASSWORD = os.environ.get('ems_key', 'chhu bboa dizs vfvg') 

# # =========================================================
# # STRIPE KEYS
# # =========================================================
# STRIPE_PUBLISHABLE_KEY = "pk_test_your_key_here"
# STRIPE_SECRET_KEY = "sk_test_your_secret_key_here"

"""
Django settings for Cord project.
Updated for Render Deployment + Flutter Support + Cloudinary Media Storage
"""
import dj_database_url
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# SECURITY SETTINGS
# =========================================================

# 1. SECRET_KEY: Try to get it from Render. If not found, use the insecure local one.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-g^-g!!08#5_(3agt4+=i=(o@miqp8jhx)4hazka(4c2+%t=z42')

# 2. DEBUG: Disable Debug mode on Render (Production), keep True locally
if 'RENDER' in os.environ:
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ['*'] # Required for Render

# =========================================================
# APPLICATION DEFINITION
# =========================================================

INSTALLED_APPS = [
    # --- CLOUDINARY APPS (Must be before staticfiles if using for static, good practice generally) ---
    'cloudinary_storage', 
    'django.contrib.staticfiles', 
    'cloudinary',
    
    # --- DEFAULT APPS ---
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    # --- THIRD PARTY APPS ---
    'rest_framework',
    'corsheaders', 
    
    # --- YOUR APPS ---
    'CordApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',       # CORS headers
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Cord.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Cord.wsgi.application'

# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    'default': dj_database_url.config(
        # Local fallback (SQLite)
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}

# =========================================================
# PASSWORDS & I18N
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =========================================================
# STATIC FILES (CSS, JS)
# =========================================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise for Static Files (CSS/JS)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False

# =========================================================
# MEDIA FILES (CLOUDINARY CONFIGURATION)
# =========================================================

# This tells Django to use Cloudinary for any ImageField/FileField
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Standard Media settings (still good to keep for local dev or reference)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================================
# CORS SETTINGS (For Flutter)
# =========================================================

CORS_ALLOW_ALL_ORIGINS = True 

# =========================================================
# EMAIL SETTINGS
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'saanandsdb@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('ems_key', 'chhu bboa dizs vfvg') 

# =========================================================
# STRIPE KEYS
# =========================================================
STRIPE_PUBLISHABLE_KEY = "pk_test_your_key_here"
STRIPE_SECRET_KEY = "sk_test_your_secret_key_here"

# settings.py
